kind: pipeline
type: kubernetes
name: default

steps:
  - name: build-and-publish
    image: plugins/docker
    settings:
      #username:
      #  from_secret: DOCKER_USERNAME
      #password:
      #  from_secret: DOCKER_PASSWORD
      repo: alpine
      tags:
        - hec
      dry_run: true
      purge: false
  - name: test
    image: aquasec/trivy:0.18.3
    #pull: never
    commands:
      - python:3.4-alpine

trigger:
  event:
    exclude:
      - pull_request
