#!/usr/bin/env bash

: "${QUERY_REPO:?Variable not set or empty}"
CLAIR_HOST=${CLAIR_HOST:-"http://clair.sys-clair:6060"}
DOCKER_AUTH_CONFIG=${DOCKER_AUTH_CONFIG:-"{\"auths\":{}}"}

echo "Scanning ${QUERY_REPO} with ${CLAIR_HOST}"

mkdir -p "${HOME}"/.docker
echo "${DOCKER_AUTH_CONFIG}" >"${HOME}"/.docker/config.json

clairctl report --host "${CLAIR_HOST}" "${QUERY_REPO}" >report

if ! [ -s report ]; then
  echo "ERROR: could't get a vulnerability report"
  exit 1
fi

found=$(grep -c ' found ' report)

if [ $found -gt 0 ]; then
  cat report
  exit 1
else
  echo "OK: No vulnerabilities found"
fi
